/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Principal.Conection;
import Principal.Kalorik;
import com.sun.corba.se.impl.orbutil.ORBConstants;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lalo_
 */
public class consultaUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form consulta_usuarios
     */
    Kalorik frame;
    Connection conection;
    private int userId;

    public consultaUsuarios() {
        initComponents();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalorik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalorik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalorik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalorik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    public void setFrame(Kalorik frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton2 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton3 = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta usuarios");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Buscar:  ");
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);
        jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);
        jPanel1.add(jSeparator1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido paterno", "Apellido materno", "Sexo", "Telefono", "Casillero", "Entrenador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Filtros");
        jPanel3.add(jLabel2);

        jPanel5.setLayout(new java.awt.GridLayout(0, 1));

        jLabel4.setText("Sexo");
        jPanel5.add(jLabel4);

        jCheckBox2.setText("Masculino");
        jPanel5.add(jCheckBox2);

        jCheckBox3.setText("Femenino");
        jPanel5.add(jCheckBox3);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        jLabel5.setText("Casillero");
        jPanel6.add(jLabel5);

        jCheckBox1.setText("Con casillero");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox1);

        jCheckBox4.setText("Sin casillero");
        jPanel6.add(jCheckBox4);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel6.setText("Entrenador");
        jPanel7.add(jLabel6);

        jCheckBox5.setText("Con entrenador");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel7.add(jCheckBox5);

        jCheckBox6.setText("Sin entrenador");
        jPanel7.add(jCheckBox6);

        jPanel3.add(jPanel7);

        add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));
        jPanel8.add(filler3);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);
        jPanel8.add(filler1);

        jButton2.setText("Editar");
        jPanel8.add(jButton2);
        jPanel8.add(filler2);

        jButton3.setText("Eliminar");
        jPanel8.add(jButton3);
        jPanel8.add(filler4);

        add(jPanel8, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame.setCard(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        conection = frame.getConexion();
        if (!jTextField1.getText().equals("")) {
            try {
                Statement select = conection.createStatement();
                ResultSet rs = select.executeQuery("select id_usuario from usuarios t1 inner join tarjetas t2 on t1.id_tarjeta = t2.id_tarjeta where uid ='" + jTextField1.getText() + "'");

                rs.next();
                userId = rs.getInt("id_usuario");

                select.close();

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());

            }
        }
        sql();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void sql() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        conection = frame.getConexion();

        try {
            Statement select = conection.createStatement();
            ResultSet rs;
            String command = "select nombre, ape_pat, ape_mat, sexo, telefono, id_locker, id_entrenador from usuarios where id_usuario is not null";
            
            if(jCheckBox2.isSelected()){
                command = command + " and sexo = 'masculino'";
            }
            if(jCheckBox3.isSelected()){
                command = command + " and sexo = 'femenino'";
            }
            if(jCheckBox1.isSelected()){
                command = command + " and id_locker is not null";
            }
            if(jCheckBox4.isSelected()){
                command = command + " and id_locker is null;";
            }
            if(jCheckBox5.isSelected()){
                command = command + " and id_entrenador = is not  null";
            }
            if(jCheckBox6.isSelected()){
                command = command + " and id_entrenador = is null";
            }
            rs = select.executeQuery(command);

            String nombre;
            String apePat;
            String apeMat;
            String sexo;
            String telefono;
            int idlocker;
            int idEntrenador;
            while (rs.next()) {

                nombre = rs.getString("nombre");
                apePat = rs.getString("ape_pat");
                apeMat = rs.getString("ape_mat");
                sexo = rs.getString("sexo");
                telefono = rs.getString("telefono");
                idlocker = rs.getInt("id_locker");
                idEntrenador = rs.getInt("id_entrenador");
                String[] data = {nombre, apePat, apeMat, sexo, telefono, String.valueOf(idlocker), String.valueOf(idEntrenador)};
                model.addRow(data);
            }

            select.close();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
