package Vistas;

import Principal.Conection;
import Principal.Kalorik;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lalo_
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    private Kalorik frame;
    private Connection conection;

    public Register() {
        initComponents();

    }

    public void setFrame(Kalorik frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgLocker = new javax.swing.ButtonGroup();
        bgEntrenador = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtApePat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtApeMat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfFecha = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jtTel = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jrMasculino = new javax.swing.JRadioButton();
        jrFemenino = new javax.swing.JRadioButton();
        filler31 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler32 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel6 = new javax.swing.JLabel();
        jtCalle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtNumEx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtNumInt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtColonia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtCiudad = new javax.swing.JTextField();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler26 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel15 = new javax.swing.JLabel();
        jtCard = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jrLockerSi = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jrEntrenadorSi = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        filler29 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler30 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel3 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton2 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));
        jPanel1.add(jSeparator3);
        jPanel1.add(jSeparator5);
        jPanel1.add(filler4);
        jPanel1.add(filler9);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jtNombre);

        jLabel3.setText("Apellido paterno");
        jPanel1.add(jLabel3);
        jPanel1.add(jtApePat);

        jLabel4.setText("Apellido materno");
        jPanel1.add(jLabel4);
        jPanel1.add(jtApeMat);

        jLabel5.setText("Fecha de nacimiento");
        jPanel1.add(jLabel5);

        jfFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/mm/d"))));
        jfFecha.setToolTipText("");
        jPanel1.add(jfFecha);

        jLabel14.setText("Telefono");
        jPanel1.add(jLabel14);
        jPanel1.add(jtTel);

        jLabel12.setText("Sexo");
        jPanel1.add(jLabel12);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        bgSexo.add(jrMasculino);
        jrMasculino.setSelected(true);
        jrMasculino.setText("Masculino");
        jPanel4.add(jrMasculino);

        bgSexo.add(jrFemenino);
        jrFemenino.setText("Femenino");
        jPanel4.add(jrFemenino);

        jPanel1.add(jPanel4);
        jPanel1.add(filler31);
        jPanel1.add(filler32);

        jLabel6.setText("Calle");
        jPanel1.add(jLabel6);
        jPanel1.add(jtCalle);

        jLabel9.setText("Numero exterior");
        jPanel1.add(jLabel9);

        jtNumEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumExActionPerformed(evt);
            }
        });
        jPanel1.add(jtNumEx);

        jLabel10.setText("Numero interior");
        jPanel1.add(jLabel10);
        jPanel1.add(jtNumInt);

        jLabel7.setText("Colonia");
        jPanel1.add(jLabel7);

        jtColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtColoniaActionPerformed(evt);
            }
        });
        jPanel1.add(jtColonia);

        jLabel8.setText("Ciudad");
        jPanel1.add(jLabel8);
        jPanel1.add(jtCiudad);
        jPanel1.add(filler25);
        jPanel1.add(filler26);

        jLabel15.setText("Card ID");
        jPanel1.add(jLabel15);
        jPanel1.add(jtCard);

        jLabel11.setText("Casillero");
        jPanel1.add(jLabel11);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        bgLocker.add(jrLockerSi);
        jrLockerSi.setText("Si");
        jPanel5.add(jrLockerSi);

        bgLocker.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButton4);

        jPanel1.add(jPanel5);

        jLabel13.setText("Entrenador");
        jPanel1.add(jLabel13);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        bgEntrenador.add(jrEntrenadorSi);
        jrEntrenadorSi.setText("Si");
        jPanel6.add(jrEntrenadorSi);

        bgEntrenador.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("No");
        jPanel6.add(jRadioButton6);

        jPanel1.add(jPanel6);
        jPanel1.add(filler29);
        jPanel1.add(filler30);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(filler3);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jPanel3.add(filler1);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jPanel3.add(filler2);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jtNumExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumExActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumExActionPerformed

    private void jtColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtColoniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtColoniaActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame.setCard(2);
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            PreparedStatement consulta;
            //Tabla direcciones
            consulta = conection.prepareStatement("INSERT INTO " + "direcciones" + "(calle, colonia, ciudad, num_exterior, num_interior) VALUES(?,?,?,?,?)");

            consulta.setString(1, jtCalle.getText());
            consulta.setString(2, jtColonia.getText());
            consulta.setString(3, jtCiudad.getText());
            consulta.setString(4, jtNumEx.getText());
            consulta.setString(5, jtNumInt.getText());
            
            consulta.execute();
            
            //Tabla tarjetas
            consulta = conection.prepareStatement("INSERT INTO " + "tarjetas" + "(uid) VALUES(?)");

            consulta.setString(1, jtCard.getText());
            
            consulta.execute();

            //Tabla usuarios
            consulta = conection.prepareStatement("INSERT INTO " + "usuarios" + "(nombre, ape_pat, ape_mat,fecha_nac, telefono, sexo ,id_locker,id_entrenador) VALUES(?,?,?,?,?,?,?,?)");

            consulta.setString(1, jtNombre.getText());
            consulta.setString(2, jtApePat.getText());
            consulta.setString(3, jtApeMat.getText());
            consulta.setString(4, jfFecha.getText());
            consulta.setString(5, jtTel.getText());
            if (jrMasculino.isSelected()) {
                consulta.setString(6, "Masculino");
            } else {
                consulta.setString(6, "Femenino");
            }

            if (jrLockerSi.isSelected()) {
                consulta.setInt(7, 0);
            }

            if (jrEntrenadorSi.isSelected()) {
                consulta.setInt(7, 0);
            }
            consulta.setInt(8, 0);

            consulta.execute();

            limpiar();
            JOptionPane.showMessageDialog(this, "Usuario registrado");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        conection = frame.getConexion();
        int cantidad;
        try {
            Statement select = conection.createStatement();
            ResultSet rs = select.executeQuery("SELECT count(*) from locker where libre  = 1");

            rs.next();
            cantidad = rs.getInt("count(*)");
            jLabel11.setText(jLabel11.getText() + " (" + cantidad + ")");
            if (cantidad == 0) {
                jrLockerSi.setEnabled(false);
                jRadioButton4.setEnabled(false);
            }

            select.close();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void limpiar() {
        jLabel11.setText("Casillero");
        jtNombre.setText("");
        jtApePat.setText("");
        jtApeMat.setText("");
        jfFecha.setText("");
        jtTel.setText("");
        jtCalle.setText("");
        jtNumEx.setText("");
        jtNumInt.setText("");
        jtColonia.setText("");
        jtCiudad.setText("");
        jtCard.setText("");

        jrLockerSi.setSelected(false);
        jRadioButton4.setSelected(false);
        jrEntrenadorSi.setSelected(false);
        jRadioButton6.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEntrenador;
    private javax.swing.ButtonGroup bgLocker;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler29;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler32;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JFormattedTextField jfFecha;
    private javax.swing.JRadioButton jrEntrenadorSi;
    private javax.swing.JRadioButton jrFemenino;
    private javax.swing.JRadioButton jrLockerSi;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JTextField jtApeMat;
    private javax.swing.JTextField jtApePat;
    private javax.swing.JTextField jtCalle;
    private javax.swing.JTextField jtCard;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtColonia;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtNumEx;
    private javax.swing.JTextField jtNumInt;
    private javax.swing.JTextField jtTel;
    // End of variables declaration//GEN-END:variables
}
