/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


import Principal.Kalorik;
import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

/**
 *
 * @author lalo_
 */
public class VistaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form VistaUsuario
     */
    Kalorik frame;
    Connection conection;
    private String anno;
    private String mes;
    private int numMes;
    private int userId;
    private static PanamaHitek_Arduino ino = new PanamaHitek_Arduino();
    private SerialPortEventListener listener;

    public VistaUsuario() {
        initComponents();
       
        numMes = 5;
        
        
        listener = new SerialPortEventListener() {
            @Override
            public void serialEvent(SerialPortEvent spe) {
                try {
                    if (ino.isMessageAvailable()) {
                        String recibe = ino.printMessage();
                        jTextField1.setText(recibe);
                        
                    }
                } catch (SerialPortException ex) {
                    Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ArduinoException ex) {
                    Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        for (String serialPort : ino.getSerialPorts()) {
            System.out.println(serialPort);
        }
        try {
            ino.arduinoRXTX("COM3", 9600, listener);
        } catch (ArduinoException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void setFrame(Kalorik frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jPanel2.add(jSeparator1);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText(" ID   ");
        jPanel4.add(jLabel1, java.awt.BorderLayout.WEST);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, java.awt.BorderLayout.EAST);
        jPanel4.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);
        jPanel2.add(jSeparator2);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridLayout(0, 1));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Semana" }));
        jPanel11.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jButton4.setText("←");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton4, java.awt.BorderLayout.WEST);

        jButton5.setText("→");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton5, java.awt.BorderLayout.EAST);

        jPanel13.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Año:     ");
        jPanel13.add(jLabel3);

        jLabel4.setText("2019");
        jPanel13.add(jLabel4);

        jPanel12.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel11);

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.CardLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mayo");
        jPanel10.add(jLabel2, java.awt.BorderLayout.CENTER);

        jButton2.setText("→");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2, java.awt.BorderLayout.EAST);

        jButton3.setText("←");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3, java.awt.BorderLayout.WEST);

        jPanel7.add(jPanel10, java.awt.BorderLayout.NORTH);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0));

        jPanel16.setLayout(new java.awt.GridLayout(0, 2));
        jPanel16.add(jSeparator5);
        jPanel16.add(jSeparator6);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Calorias quemadas");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), null));
        jPanel16.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel16.add(jLabel7);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tiempo de ejercicio");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), null));
        jPanel16.add(jLabel8);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel16.add(jLabel9);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Maquina mas usada");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 153, 153), null));
        jPanel16.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel16.add(jLabel11);

        jSeparator3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel16.add(jSeparator3);

        jSeparator4.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel16.add(jSeparator4);

        jPanel15.add(jPanel16);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maquina", "Calorias quemadas", "Tiempo de uso"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel17.add(jScrollPane1);

        jPanel15.add(jPanel17);

        jPanel7.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7, "card2");

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("27 - 2");
        jPanel14.add(jLabel5, java.awt.BorderLayout.CENTER);

        jButton6.setText("→");
        jPanel14.add(jButton6, java.awt.BorderLayout.EAST);

        jButton7.setText("←");
        jPanel14.add(jButton7, java.awt.BorderLayout.WEST);

        jPanel8.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jPanel19.setLayout(new java.awt.GridLayout(0, 2));

        jSeparator7.setForeground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.borderColor"));
        jSeparator7.setToolTipText("");
        jSeparator7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator7.setFocusCycleRoot(true);
        jPanel19.add(jSeparator7);

        jSeparator8.setForeground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.borderColor"));
        jSeparator8.setToolTipText("");
        jSeparator8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator8.setFocusCycleRoot(true);
        jPanel19.add(jSeparator8);

        jLabel12.setText("Calorias quemadas");
        jPanel19.add(jLabel12);

        jLabel13.setText("jLabel7");
        jPanel19.add(jLabel13);

        jLabel14.setText("Tiempo de ejercicio");
        jPanel19.add(jLabel14);

        jLabel15.setText("jLabel9");
        jPanel19.add(jLabel15);

        jLabel16.setText("Maquina mas usada");
        jPanel19.add(jLabel16);

        jLabel17.setText("jLabel11");
        jPanel19.add(jLabel17);

        jSeparator9.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel19.add(jSeparator9);

        jSeparator10.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel19.add(jSeparator10);

        jPanel18.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Jueves");
        jPanel21.add(jLabel18, java.awt.BorderLayout.CENTER);

        jButton8.setText("→");
        jPanel21.add(jButton8, java.awt.BorderLayout.EAST);

        jButton9.setText("←");
        jPanel21.add(jButton9, java.awt.BorderLayout.WEST);

        jPanel20.add(jPanel21, java.awt.BorderLayout.NORTH);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Maquina", "Calorias quemadas", "Tiempo de uso"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel20.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20);

        jPanel8.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, "card3");

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        anno = String.valueOf(Integer.parseInt(jLabel4.getText()) - 1);
        jLabel4.setText(anno);
        sql();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conection = frame.getConexion();

        try {
            Statement select = conection.createStatement();
            ResultSet rs = select.executeQuery("select id_usuario from usuarios t1 inner join tarjetas t2 on t1.id_tarjeta = t2.id_tarjeta where uid ='" + jTextField1.getText() + "'");

            rs.next();
            userId = rs.getInt("id_usuario");

            select.close();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }
        sql();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        anno = String.valueOf(Integer.parseInt(jLabel4.getText()) + 1);
        jLabel4.setText(anno);      // TODO add your handling code here:
        sql();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cambiarMes(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cambiarMes(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cambiarMes(int meses) {

        switch (meses) {
            case 0:
                numMes--;
                break;
            case 1:
                numMes++;
                break;
        }
        if (numMes > 12) {
            numMes = 1;
        } else if (numMes < 1) {
            numMes = 12;
        }

        switch (numMes) {
            case 1:
                jLabel2.setText("Enero");
                mes = "01";
                break;
            case 2:
                jLabel2.setText("Febrero");
                mes = "02";
                break;
            case 3:
                jLabel2.setText("Marzo");
                mes = "03";
                break;
            case 4:
                jLabel2.setText("Abril");
                mes = "04";
                break;
            case 5:
                jLabel2.setText("Mayo");
                mes = "05";
                break;
            case 6:
                jLabel2.setText("Junio");
                mes = "06";
                break;
            case 7:
                jLabel2.setText("Julio");
                mes = "07";
                break;
            case 8:
                jLabel2.setText("Agosto");
                mes = "08";
                break;
            case 9:
                jLabel2.setText("Septiembre");
                mes = "09";
                break;
            case 10:
                jLabel2.setText("Octubre");
                mes = "10";
                break;
            case 11:
                jLabel2.setText("Noviembre");
                mes = "11";
                break;
            case 12:
                jLabel2.setText("Diciembre");
                mes = "12";
                break;
        }
        sql();
        
    }
     private void sql(){
         conection = frame.getConexion();
        int cantidad;
        try {
            Statement select = conection.createStatement();
            ResultSet rs = select.executeQuery("SELECT calorias(" + userId + "," + anno + "," + mes + ") as calorias");

            rs.next();
            cantidad = rs.getInt("calorias");
            jLabel7.setText(String.valueOf(cantidad));

            rs = select.executeQuery("SELECT tiempoEjercicio(" + userId + "," + anno + "," + mes + ") as tiempo");
            rs.next();
            cantidad = rs.getInt("tiempo");
            jLabel9.setText(String.valueOf(cantidad));

            

            rs = select.executeQuery("select id_maquina, tiempo, calorias from estadisticas_usuario where id_usuario =" + userId);

            int maquina;
            int tiempo;
            int calorias;

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            while (rs.next()) {

                maquina = rs.getInt("id_maquina");
                tiempo = rs.getInt("tiempo");
                calorias = rs.getInt("calorias");
                String[] data = {String.valueOf(maquina), String.valueOf(calorias), String.valueOf(tiempo)};
                model.addRow(data);
            }

            select.close();

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());

        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
